### ISSUE TITLE
busboy finish event

### ISSUE THREAD

**Issue by vivekgs2007** [mscdex/connect-busboy#12]
Hi,
My understanding is that. finish event will trigger after file and field event completes?
Is their any other event that will fire after field and file event completes. I need to send the response to the client after all events completes.

This is the very critical one. Please let me know
 
Thanks,
Vivek

**Comment by mscdex** [comment]
The `finish` event fires once the entire request has been parsed and if you attached a `file` event handler, after all file streams have been completely read.
