### ISSUE TITLE
Application freezes when no or not all files are uploaded

### ISSUE THREAD

**Issue by kuba12kozak** [mscdex/connect-busboy#14]
Hi. I've got the following problem: http://stackoverflow.com/questions/33712020/my-application-using-busboy-freezes-when-no-files-uploaded
When uploading three files everything is ok, but when one or more files are missing, the application is freezing and "finish" section doesn't even start.

**Comment by mscdex** [comment]
The problem is that you're ignoring the file stream in both your `else` conditions *and* in your missing `default` case. For those you should at least `file.resume();` so that the parser can continue to process the rest of the request data.

**Comment by kuba12kozak** [comment]
It helped. Thank you very much.
