### ISSUE TITLE
How, to change encoding, for support windows-1251

### ISSUE THREAD

**Issue by K3ler** [mscdex/connect-busboy#16]
You, answer the question
http://stackoverflow.com/questions/26084373/error-while-process-req-with-charset-windows-1251

Can, you write a little example, for urlencoded, supports windows-1251?

**Comment by mscdex** [comment]
`busboy` has a `defCharset` option that you can change (from the default of `'utf8'`):

```js
var Busboy = require('busboy');
var busboy = new Busboy({ defCharset: 'windows-1251', headers: ... });
```

If you're using `connect-busboy`, then you can pass settings directly to `busboy`:

```js
var busboy = require('connect-busboy');
app.use(busboy({ defCharset: 'windows-1251' }));
```

**Comment by K3ler** [comment]
sorry, but i got same error 415  unsupported charset "WINDOWS-1251"

in route, i set

```
var Busboy = require('busboy');


var payment = {

	result : function(req, res, next) {

		var busboy = new Busboy({ headers: req.headers,  });
	    
	    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
	      console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype);
	      file.on('data', function(data) {
	        console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
	      });
	      file.on('end', function() {
	        console.log('File [' + fieldname + '] Finished');
	      });
	    });
	    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) {
	      console.log('Field [' + fieldname + ']: value: ' + val);
	    });
	    busboy.on('finish', function() {
	      console.log('Done parsing form!');
	      res.end();
	    });
	    req.pipe(busboy);
	}
}

module.exports = payment;
```

i asked semilar question 

http://stackoverflow.com/questions/37056794/bodyparser-urlencode-in-express-4-and-encoding-windows-1251

thanks for help

**Comment by mscdex** [comment]
If you're getting the same error as the one you show in your SO question, then you're still using `body-parser` instead of (or before) `busboy` then. `busboy` would not generate an error like that.

**Comment by K3ler** [comment]
Yeesssssssssssss! WORK! You save my life! Thanks!

**Comment by mscdex** [comment]
Glad to hear you got it working!
