### ISSUE TITLE
async routing function stops the busboy events from firing

### ISSUE THREAD

**Issue by sirisian** [mscdex/connect-busboy#18]
This works:
```js
app.post(`/`, async (req, res) => { /* busboy code */ });
```
This doesn't:
```js
app.post(`/`, async (req, res) => { await (async () => {})(); /* busboy code */ });
```
Seems like the act of awaiting breaks how busboy works. I can't figure out why though.

**Comment by mscdex** [comment]
I don't know anything about the new ES async functions, generators, and all that. This module just uses normal callbacks. It's probably just a misunderstanding with the language if it's working for you with other coding styles.
