### ISSUE TITLE
can not read all chunk of the files

### ISSUE THREAD

**Issue by mursal-shydv** [mscdex/connect-busboy#23]
![Screenshot from 2021-12-22 12-41-51](https://user-images.githubusercontent.com/80178352/147087621-1b5cd845-fa9a-4f6d-9c07-1e1b8c4c7152.png)

Hello,
after updating connect-busboy from 0.0.2 to 1.0.0, I am having an issue. The problem is that this code sometimes works but sometimes does not. seems like something gets broken while uploading a file with API and just half of the file reaches the server and the close event does not trigger. if you call the API with the same file let's say 5-6 times, this error will occur just once.

**Comment by mscdex** [comment]
This should be posted to the `busboy` issue tracker instead.
