### ISSUE TITLE
Extending this to middleware that automatically fetches all attached files and fields

### ISSUE THREAD

**Issue by jhorbulyk** [mscdex/connect-busboy#4]
I stumbled across this middleware because I am looking for a middleware that automatically grabs fields and attached files from a multipart upload but keeps the file contents available in memory (i.e. doesn't write them to disk).  It looks like it is possible to extend this middleware to do the job.  However, this seems like a very general problem and so I'm wondering if it makes sense to extend this middleware with this functionality.  Thoughts?

**Comment by mscdex** [comment]
There is also [`multer`](https://github.com/expressjs/multer) which supports buffering in-memory now too.
