### ISSUE TITLE
Using busboy special event 'filesLimit' with nodejs and express.

### ISSUE THREAD

**Issue by saurabhghewari** [mscdex/connect-busboy#7]
How to use busboy special event 'filesLimit' in nodejs?

**Comment by simong** [comment]
This is easier said than done. AFAICT, by the time you can plug in an event listener in your own middleware, the event has already fired, hasn't it?

**Comment by mscdex** [comment]
@simong It definitely shouldn't if you are *not* using `immediate: true` because then you are in control of when the request gets piped to the busboy instance, so there should be plenty of time to add listeners before piping.

**Comment by mscdex** [comment]
Closing this for now. If you are missing these kinds of events when `immediate: true` is not set, let me know.
