### ISSUE TITLE
file event is not triggered

### ISSUE THREAD

**Issue by kdelemme** [mscdex/connect-busboy#8]
Hello,

I have a simple route like this:

```
router.post('/locations/file', busboy(), function(req, res, next) {
   console.log('here');

    req.busboy.on('file', function (fieldname, file, filename) {
        console.log('bar');
        var filePath = path.join(os.tmpdir(), filename);
        fstream = fs.createWriteStream(filePath);
        file.pipe(fstream);

       fstream.on('close', function () {
           console.log('foo');
       });
    });

    req.pipe(req.busboy);
});
```

And I have a weird behaviour: The file event is not triggered everytime (with the same file and the same upload form). but the 'here' log is displayed

I'm using express 4.6.1, connect-busboy 0.0.2 with busboy 0.2.9. 

Thanks

**Comment by vivian-ho** [comment]
I do see data when doing this 
req.on('data', function(d) { 
  console.dir(''+d); 
});

but req.busboy.on('file' is not firing...what could be wrong

**Comment by lakshaygaur** [comment]
@kdelemme How did you configure it exactly cause Im having the same issue with express.

**Comment by shubham-gulati** [comment]
hey, am getting same problem. My console.dir(req.headers['content-type']) shows below
application/x-www-form-urlencoded; charset=UTF-8

Can someone help me fetching form data?
